### ISSUE TITLE
Include metadata key for crossing uploaded files to indicate it was uploaded with crossing

### ISSUE THREAD

**Issue by jsywulak** [stelligent/crossing#11]
We need a way to detect if a file has been encrypted and uploaded using crossing. AWS CSE _does_ include a number of tags, but those tags are used for _any_ AWS CSE operation, and is not a accurate indicator if Crossing was _specifically_ used to encrypt and upload that data.

We'd like to see an `x-crossing-uploaded` metadata key (or something similar) that will definitively identify data as uploaded via Crossing.

**Comment by kmonihen** [comment]
This has been pushed to master and built out as crossing 0.0.8
