### ISSUE TITLE
Seamless downloading of unencrypted files

### ISSUE THREAD

**Issue by jsywulak** [stelligent/crossing#13]
Sometimes we will store a mix of encrypted and unencrypted files in the same bucket. This is common as we migrate workflows to use crossing, but there are some legacy applications that use the same bucket. It would be nice if crossing could download objects that were not encrypted, and just pass them through.

A warning that it was downloaded as plaintext would be helpful as well, just in case I think that a file should be encrypted but isn't.

**Comment by kmonihen** [comment]
#16

**Comment by kmonihen** [comment]
Fixed in 0.1.0
