### ISSUE TITLE
Multi-file download support

### ISSUE THREAD

**Issue by jsywulak** [stelligent/crossing#15]
It's very common that we'll need to download multiple crossing-encrypted files during a workflow. It would be nice if we could pass in all the files we want to download and have crossing get them in a single go, rather than having to make multiple calls to crossing to get them all downloaded.

**Comment by kmonihen** [comment]
Added the ability to get and put multiple files using get_multiple and put_multiple in branch https://github.com/stelligent/crossing/tree/download-unencrypted-files

**Comment by kmonihen** [comment]
Still need to add a command line parameter for lists of files, like --files

**Comment by kmonihen** [comment]
Fixed in 0.1.0
